-- MySQL Script generated by MySQL Workbench
-- Mon Jul 27 15:06:59 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema it_helpdesk_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema it_helpdesk_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `it_helpdesk_db` DEFAULT CHARACTER SET utf8mb3 ;
USE `it_helpdesk_db` ;

-- -----------------------------------------------------
-- Table `it_helpdesk_db`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_helpdesk_db`.`roles` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `it_helpdesk_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_helpdesk_db`.`users` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC) VISIBLE,
  INDEX `users_role_id_foreign` (`role_id` ASC) VISIBLE,
  CONSTRAINT `users_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `it_helpdesk_db`.`roles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `it_helpdesk_db`.`activity_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_helpdesk_db`.`activity_logs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `action` VARCHAR(100) NOT NULL,
  `target_type` VARCHAR(50) NOT NULL,
  `target_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `LogsUser_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `logs_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `it_helpdesk_db`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `it_helpdesk_db`.`cache`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_helpdesk_db`.`cache` (
  `key` VARCHAR(255) NOT NULL,
  `value` MEDIUMTEXT NOT NULL,
  `expiration` BIGINT NOT NULL,
  PRIMARY KEY (`key`),
  INDEX `cache_expiration_index` (`expiration` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `it_helpdesk_db`.`cache_locks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_helpdesk_db`.`cache_locks` (
  `key` VARCHAR(255) NOT NULL,
  `owner` VARCHAR(255) NOT NULL,
  `expiration` BIGINT NOT NULL,
  PRIMARY KEY (`key`),
  INDEX `cache_locks_expiration_index` (`expiration` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `it_helpdesk_db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_helpdesk_db`.`categories` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `it_helpdesk_db`.`failed_jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_helpdesk_db`.`failed_jobs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(255) NOT NULL,
  `connection` VARCHAR(255) NOT NULL,
  `queue` VARCHAR(255) NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `exception` LONGTEXT NOT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `failed_jobs_uuid_unique` (`uuid` ASC) VISIBLE,
  INDEX `failed_jobs_connection_queue_failed_at_index` (`connection` ASC, `queue` ASC, `failed_at` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `it_helpdesk_db`.`job_batches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_helpdesk_db`.`job_batches` (
  `id` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `total_jobs` INT NOT NULL,
  `pending_jobs` INT NOT NULL,
  `failed_jobs` INT NOT NULL,
  `failed_job_ids` LONGTEXT NOT NULL,
  `options` MEDIUMTEXT NULL DEFAULT NULL,
  `cancelled_at` INT NULL DEFAULT NULL,
  `created_at` INT NOT NULL,
  `finished_at` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `it_helpdesk_db`.`jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_helpdesk_db`.`jobs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `queue` VARCHAR(255) NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `attempts` SMALLINT UNSIGNED NOT NULL,
  `reserved_at` INT UNSIGNED NULL DEFAULT NULL,
  `available_at` INT UNSIGNED NOT NULL,
  `created_at` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `jobs_queue_index` (`queue` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `it_helpdesk_db`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_helpdesk_db`.`migrations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `it_helpdesk_db`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_helpdesk_db`.`notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `message` VARCHAR(255) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `is_read` TINYINT NOT NULL DEFAULT '0',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `notificationUser_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `notification_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `it_helpdesk_db`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `it_helpdesk_db`.`password_reset_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_helpdesk_db`.`password_reset_tokens` (
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `it_helpdesk_db`.`priorities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_helpdesk_db`.`priorities` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `it_helpdesk_db`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_helpdesk_db`.`sessions` (
  `id` VARCHAR(255) NOT NULL,
  `user_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `ip_address` VARCHAR(45) NULL DEFAULT NULL,
  `user_agent` TEXT NULL DEFAULT NULL,
  `payload` LONGTEXT NOT NULL,
  `last_activity` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `sessions_user_id_index` (`user_id` ASC) VISIBLE,
  INDEX `sessions_last_activity_index` (`last_activity` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `it_helpdesk_db`.`statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_helpdesk_db`.`statuses` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `it_helpdesk_db`.`tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_helpdesk_db`.`tickets` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `reference_no` VARCHAR(45) NOT NULL,
  `title` VARCHAR(150) NOT NULL,
  `description` TEXT NOT NULL,
  `category_id` BIGINT UNSIGNED NOT NULL,
  `priority_id` BIGINT UNSIGNED NOT NULL,
  `status_id` BIGINT UNSIGNED NOT NULL,
  `employee_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `assigned_to` BIGINT UNSIGNED NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tickets_reference_no_unique` (`reference_no` ASC) VISIBLE,
  INDEX `tickets_employee_id_index` (`employee_id` ASC) VISIBLE,
  INDEX `tickets_assigned_to_index` (`assigned_to` ASC) VISIBLE,
  INDEX `tickets_category_id_foreign` (`category_id` ASC) VISIBLE,
  INDEX `tickets_priority_id_foreign` (`priority_id` ASC) VISIBLE,
  INDEX `tickets_status_id_foreign` (`status_id` ASC) VISIBLE,
  CONSTRAINT `tickets_assigned_to_foreign`
    FOREIGN KEY (`assigned_to`)
    REFERENCES `it_helpdesk_db`.`users` (`id`),
  CONSTRAINT `tickets_category_id_foreign`
    FOREIGN KEY (`category_id`)
    REFERENCES `it_helpdesk_db`.`categories` (`id`),
  CONSTRAINT `tickets_employee_id_foreign`
    FOREIGN KEY (`employee_id`)
    REFERENCES `it_helpdesk_db`.`users` (`id`),
  CONSTRAINT `tickets_priority_id_foreign`
    FOREIGN KEY (`priority_id`)
    REFERENCES `it_helpdesk_db`.`priorities` (`id`),
  CONSTRAINT `tickets_status_id_foreign`
    FOREIGN KEY (`status_id`)
    REFERENCES `it_helpdesk_db`.`statuses` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `it_helpdesk_db`.`ticket_attachments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_helpdesk_db`.`ticket_attachments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ticket_id` BIGINT UNSIGNED NOT NULL,
  `file_path` VARCHAR(255) NOT NULL,
  `file_type` VARCHAR(50) NOT NULL,
  `filesize` BIGINT NOT NULL,
  `uploaded_by` BIGINT UNSIGNED NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `ticket_attachments_ticket_id_index` (`ticket_id` ASC) VISIBLE,
  INDEX `ticket_attachments_uploaded_by_index` (`uploaded_by` ASC) VISIBLE,
  CONSTRAINT `ticket_attachments_ticket_id_foreign`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `it_helpdesk_db`.`tickets` (`id`),
  CONSTRAINT `ticket_attachments_uploaded_by_foreign`
    FOREIGN KEY (`uploaded_by`)
    REFERENCES `it_helpdesk_db`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `it_helpdesk_db`.`ticket_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it_helpdesk_db`.`ticket_comments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ticket_id` BIGINT UNSIGNED NOT NULL,
  `user_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `ticket_comments_ticket_id_index` (`ticket_id` ASC) VISIBLE,
  INDEX `ticket_comments_user_id_index` (`user_id` ASC) VISIBLE,
  CONSTRAINT `ticket_comments_ticket_id_foreign`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `it_helpdesk_db`.`tickets` (`id`),
  CONSTRAINT `ticket_comments_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `it_helpdesk_db`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
